package io.github.dimidrol

const val DEFAULT_SAMPLE_PERIOD_MS = 15_000L
const val DEFAULT_MEMORY_THRESHOLD_MB = 256L
const val DEFAULT_STORAGE_THRESHOLD_MB = 1024L
const val DEFAULT_CPU_OVERLOAD_THRESHOLD_PERCENT = 90f
const val DEFAULT_BATTERY_LOW_THRESHOLD_PERCENT = 20
const val DEFAULT_BATTERY_TEMPERATURE_THRESHOLD_C = 45f

const val BYTES_IN_MB = 1024L * 1024L
